# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import smtpcom
from smtpcom.models.get_api_keys import GetApiKeys  # noqa: E501
from smtpcom.rest import ApiException

class TestGetApiKeys(unittest.TestCase):
    """GetApiKeys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetApiKeys
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = smtpcom.models.get_api_keys.GetApiKeys()  # noqa: E501
        if include_optional :
            return GetApiKeys(
                status = '0', 
                data = smtpcom.models.get_api_keys_data.GetApiKeysData(
                    items = [
                        smtpcom.models.get_api_keys_data_items.GetApiKeysDataItems(
                            status = '0', 
                            description = '0', 
                            key = '0', 
                            date_created = '0', )
                        ], )
            )
        else :
            return GetApiKeys(
        )

    def testGetApiKeys(self):
        """Test GetApiKeys"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
