# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import smtp
from smtp.api.alerts_api import AlertsApi  # noqa: E501
from smtp.rest import ApiException


class TestAlertsApi(unittest.TestCase):
    """AlertsApi unit test stubs"""

    def setUp(self):
        self.api = smtp.api.alerts_api.AlertsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_alerts_alert_id_delete(self):
        """Test case for v4_alerts_alert_id_delete

        Delete Alert  # noqa: E501
        """
        pass

    def test_v4_alerts_alert_id_get(self):
        """Test case for v4_alerts_alert_id_get

        Get Alert Details  # noqa: E501
        """
        pass

    def test_v4_alerts_alert_id_patch(self):
        """Test case for v4_alerts_alert_id_patch

        Update Alert Details  # noqa: E501
        """
        pass

    def test_v4_alerts_get(self):
        """Test case for v4_alerts_get

        List All Allerts  # noqa: E501
        """
        pass

    def test_v4_alerts_post(self):
        """Test case for v4_alerts_post

        Create New Alert  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
