# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import smtp
from smtp.models.get_callback_response import GetCallbackResponse  # noqa: E501
from smtp.rest import ApiException

class TestGetCallbackResponse(unittest.TestCase):
    """GetCallbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetCallbackResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = smtp.models.get_callback_response.GetCallbackResponse()  # noqa: E501
        if include_optional :
            return GetCallbackResponse(
                status = '0', 
                data = smtp.models.get_callback_response_data.GetCallbackResponseData(
                    items = [
                        smtp.models.get_callback_response_data_items.GetCallbackResponseDataItems(
                            medium = 'http', 
                            event = '0', 
                            channel = '0', 
                            address = '0', 
                            aws_data = '0', )
                        ], )
            )
        else :
            return GetCallbackResponse(
        )

    def testGetCallbackResponse(self):
        """Test GetCallbackResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
