# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import smtpcom
from smtpcom.api.statistics_api import StatisticsApi  # noqa: E501
from smtpcom.rest import ApiException


class TestStatisticsApi(unittest.TestCase):
    """StatisticsApi unit test stubs"""

    def setUp(self):
        self.api = smtpcom.api.statistics_api.StatisticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_stats_duration_slice_slice_specifier_group_by_get(self):
        """Test case for v4_stats_duration_slice_slice_specifier_group_by_get

        Return event aggregates for the specified slices and duration. Slices can be chained.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
