# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import smtpcom
from smtpcom.api.account_api import AccountApi  # noqa: E501
from smtpcom.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = smtpcom.api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_account_contact_patch(self):
        """Test case for v4_account_contact_patch

        Update Account Details  # noqa: E501
        """
        pass

    def test_v4_account_get(self):
        """Test case for v4_account_get

        Get Account Details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
