# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import smtpcom
from smtpcom.models.v4_messages_body import V4MessagesBody  # noqa: E501
from smtpcom.rest import ApiException

class TestV4MessagesBody(unittest.TestCase):
    """V4MessagesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V4MessagesBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = smtpcom.models.v4_messages_body.V4MessagesBody()  # noqa: E501
        if include_optional :
            return V4MessagesBody(
                parts = [
                    smtpcom.models.V4MessagesBodyParts(
                        version = '0', 
                        type = '0', 
                        charset = '0', 
                        encoding = '0', 
                        content = '0', )
                    ], 
                attachments = [
                    smtpcom.models.V4MessagesBodyAttachments(
                        version = '0', 
                        type = '0', 
                        disposition = '0', 
                        filename = '0', 
                        cid = '0', 
                        content = '0', )
                    ]
            )
        else :
            return V4MessagesBody(
        )

    def testV4MessagesBody(self):
        """Test V4MessagesBody"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
