# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import smtp
from smtp.api.api_keys_api import APIKeysApi  # noqa: E501
from smtp.rest import ApiException


class TestAPIKeysApi(unittest.TestCase):
    """APIKeysApi unit test stubs"""

    def setUp(self):
        self.api = smtp.api.api_keys_api.APIKeysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_api_key(self):
        """Test case for get_api_key

        Get API Key Details  # noqa: E501
        """
        pass

    def test_v4_api_keys_api_key_delete(self):
        """Test case for v4_api_keys_api_key_delete

        Delete an API Key  # noqa: E501
        """
        pass

    def test_v4_api_keys_api_key_patch(self):
        """Test case for v4_api_keys_api_key_patch

        Update API Key  # noqa: E501
        """
        pass

    def test_v4_api_keys_get(self):
        """Test case for v4_api_keys_get

        List All API Keys  # noqa: E501
        """
        pass

    def test_v4_api_keys_post(self):
        """Test case for v4_api_keys_post

        Create a New API Key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
