# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import smtp
from smtp.models.get_alert_response_data_items import GetAlertResponseDataItems  # noqa: E501
from smtp.rest import ApiException

class TestGetAlertResponseDataItems(unittest.TestCase):
    """GetAlertResponseDataItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetAlertResponseDataItems
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = smtp.models.get_alert_response_data_items.GetAlertResponseDataItems()  # noqa: E501
        if include_optional :
            return GetAlertResponseDataItems(
                type = 'monthly_quota', 
                threshold = '0.5', 
                alert_id = '0'
            )
        else :
            return GetAlertResponseDataItems(
        )

    def testGetAlertResponseDataItems(self):
        """Test GetAlertResponseDataItems"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
