# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import smtpcom
from smtpcom.api.channels_api import ChannelsApi  # noqa: E501
from smtpcom.rest import ApiException


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = smtpcom.api.channels_api.ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sender(self):
        """Test case for get_sender

        Get Channel Details  # noqa: E501
        """
        pass

    def test_v4_channels_get(self):
        """Test case for v4_channels_get

        Get All Channels  # noqa: E501
        """
        pass

    def test_v4_channels_name_delete(self):
        """Test case for v4_channels_name_delete

        Delete a Channel  # noqa: E501
        """
        pass

    def test_v4_channels_name_patch(self):
        """Test case for v4_channels_name_patch

        Update Channel Details  # noqa: E501
        """
        pass

    def test_v4_channels_post(self):
        """Test case for v4_channels_post

        Create a New Channel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
