# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import smtp
from smtp.api.callbacks_api import CallbacksApi  # noqa: E501
from smtp.rest import ApiException


class TestCallbacksApi(unittest.TestCase):
    """CallbacksApi unit test stubs"""

    def setUp(self):
        self.api = smtp.api.callbacks_api.CallbacksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v4_callbacks_delete(self):
        """Test case for v4_callbacks_delete

        Delete All Callbacks  # noqa: E501
        """
        pass

    def test_v4_callbacks_event_delete(self):
        """Test case for v4_callbacks_event_delete

        Delete Callback  # noqa: E501
        """
        pass

    def test_v4_callbacks_event_get(self):
        """Test case for v4_callbacks_event_get

        Get Callback Details  # noqa: E501
        """
        pass

    def test_v4_callbacks_event_patch(self):
        """Test case for v4_callbacks_event_patch

        Update Callback Details  # noqa: E501
        """
        pass

    def test_v4_callbacks_event_post(self):
        """Test case for v4_callbacks_event_post

        Create Callback  # noqa: E501
        """
        pass

    def test_v4_callbacks_get(self):
        """Test case for v4_callbacks_get

        List All Callbacks  # noqa: E501
        """
        pass

    def test_v4_callbacks_log_get(self):
        """Test case for v4_callbacks_log_get

        View Callback Logs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
