# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
# command to run tests
script: pytest --cov=smtp
after_success:
  - bash <(curl -s https://codecov.io/bash -t 7ae04124-21f9-4859-887b-70e509c8fe98)