# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from smtpcom.configuration import Configuration


class APIKey(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'status': 'str',
        'descrption': 'str',
        'key': 'str',
        'date_created': 'str'
    }

    attribute_map = {
        'status': 'status',
        'descrption': 'descrption',
        'key': 'key',
        'date_created': 'date_created'
    }

    def __init__(self, status=None, descrption=None, key=None, date_created=None, local_vars_configuration=None):  # noqa: E501
        """APIKey - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._status = None
        self._descrption = None
        self._key = None
        self._date_created = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if descrption is not None:
            self.descrption = descrption
        if key is not None:
            self.key = key
        if date_created is not None:
            self.date_created = date_created

    @property
    def status(self):
        """Gets the status of this APIKey.  # noqa: E501

        Current status of the API key  # noqa: E501

        :return: The status of this APIKey.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this APIKey.

        Current status of the API key  # noqa: E501

        :param status: The status of this APIKey.  # noqa: E501
        :type status: str
        """

        self._status = status

    @property
    def descrption(self):
        """Gets the descrption of this APIKey.  # noqa: E501

        Description for API key  # noqa: E501

        :return: The descrption of this APIKey.  # noqa: E501
        :rtype: str
        """
        return self._descrption

    @descrption.setter
    def descrption(self, descrption):
        """Sets the descrption of this APIKey.

        Description for API key  # noqa: E501

        :param descrption: The descrption of this APIKey.  # noqa: E501
        :type descrption: str
        """

        self._descrption = descrption

    @property
    def key(self):
        """Gets the key of this APIKey.  # noqa: E501

        The actual API key value  # noqa: E501

        :return: The key of this APIKey.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this APIKey.

        The actual API key value  # noqa: E501

        :param key: The key of this APIKey.  # noqa: E501
        :type key: str
        """

        self._key = key

    @property
    def date_created(self):
        """Gets the date_created of this APIKey.  # noqa: E501

        Timestamp of when the API key was first created.  # noqa: E501

        :return: The date_created of this APIKey.  # noqa: E501
        :rtype: str
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this APIKey.

        Timestamp of when the API key was first created.  # noqa: E501

        :param date_created: The date_created of this APIKey.  # noqa: E501
        :type date_created: str
        """

        self._date_created = date_created

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, APIKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, APIKey):
            return True

        return self.to_dict() != other.to_dict()
