# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from smtpcom.configuration import Configuration


class GetDomainDetailsResponseData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'domain_name': 'str',
        'enabled': 'bool'
    }

    attribute_map = {
        'domain_name': 'domain_name',
        'enabled': 'enabled'
    }

    def __init__(self, domain_name=None, enabled=None, local_vars_configuration=None):  # noqa: E501
        """GetDomainDetailsResponseData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._domain_name = None
        self._enabled = None
        self.discriminator = None

        if domain_name is not None:
            self.domain_name = domain_name
        if enabled is not None:
            self.enabled = enabled

    @property
    def domain_name(self):
        """Gets the domain_name of this GetDomainDetailsResponseData.  # noqa: E501

        Registered domain name  # noqa: E501

        :return: The domain_name of this GetDomainDetailsResponseData.  # noqa: E501
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name):
        """Sets the domain_name of this GetDomainDetailsResponseData.

        Registered domain name  # noqa: E501

        :param domain_name: The domain_name of this GetDomainDetailsResponseData.  # noqa: E501
        :type domain_name: str
        """

        self._domain_name = domain_name

    @property
    def enabled(self):
        """Gets the enabled of this GetDomainDetailsResponseData.  # noqa: E501

        Flag indicating whether the domain is enabled for the given account  # noqa: E501

        :return: The enabled of this GetDomainDetailsResponseData.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this GetDomainDetailsResponseData.

        Flag indicating whether the domain is enabled for the given account  # noqa: E501

        :param enabled: The enabled of this GetDomainDetailsResponseData.  # noqa: E501
        :type enabled: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetDomainDetailsResponseData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetDomainDetailsResponseData):
            return True

        return self.to_dict() != other.to_dict()
