# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from smtpcom.configuration import Configuration


class MessagesResponseDataMsgData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'rcpt_to': 'str',
        '_from': 'str',
        'subject': 'str'
    }

    attribute_map = {
        'rcpt_to': 'rcpt_to',
        '_from': 'from',
        'subject': 'subject'
    }

    def __init__(self, rcpt_to=None, _from=None, subject=None, local_vars_configuration=None):  # noqa: E501
        """MessagesResponseDataMsgData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._rcpt_to = None
        self.__from = None
        self._subject = None
        self.discriminator = None

        if rcpt_to is not None:
            self.rcpt_to = rcpt_to
        if _from is not None:
            self._from = _from
        if subject is not None:
            self.subject = subject

    @property
    def rcpt_to(self):
        """Gets the rcpt_to of this MessagesResponseDataMsgData.  # noqa: E501

        Email address of the recipient  # noqa: E501

        :return: The rcpt_to of this MessagesResponseDataMsgData.  # noqa: E501
        :rtype: str
        """
        return self._rcpt_to

    @rcpt_to.setter
    def rcpt_to(self, rcpt_to):
        """Sets the rcpt_to of this MessagesResponseDataMsgData.

        Email address of the recipient  # noqa: E501

        :param rcpt_to: The rcpt_to of this MessagesResponseDataMsgData.  # noqa: E501
        :type rcpt_to: str
        """

        self._rcpt_to = rcpt_to

    @property
    def _from(self):
        """Gets the _from of this MessagesResponseDataMsgData.  # noqa: E501

        Email address of the sender  # noqa: E501

        :return: The _from of this MessagesResponseDataMsgData.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this MessagesResponseDataMsgData.

        Email address of the sender  # noqa: E501

        :param _from: The _from of this MessagesResponseDataMsgData.  # noqa: E501
        :type _from: str
        """

        self.__from = _from

    @property
    def subject(self):
        """Gets the subject of this MessagesResponseDataMsgData.  # noqa: E501

        Message subject  # noqa: E501

        :return: The subject of this MessagesResponseDataMsgData.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this MessagesResponseDataMsgData.

        Message subject  # noqa: E501

        :param subject: The subject of this MessagesResponseDataMsgData.  # noqa: E501
        :type subject: str
        """

        self._subject = subject

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessagesResponseDataMsgData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MessagesResponseDataMsgData):
            return True

        return self.to_dict() != other.to_dict()
