# coding: utf-8

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from smtpcom.configuration import Configuration


class MessagesResponseDataAbuseComplaints(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'report_time': 'str',
        'provider': 'str'
    }

    attribute_map = {
        'report_time': 'report_time',
        'provider': 'provider'
    }

    def __init__(self, report_time=None, provider=None, local_vars_configuration=None):  # noqa: E501
        """MessagesResponseDataAbuseComplaints - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._report_time = None
        self._provider = None
        self.discriminator = None

        if report_time is not None:
            self.report_time = report_time
        if provider is not None:
            self.provider = provider

    @property
    def report_time(self):
        """Gets the report_time of this MessagesResponseDataAbuseComplaints.  # noqa: E501

        Time when the complaint was made  # noqa: E501

        :return: The report_time of this MessagesResponseDataAbuseComplaints.  # noqa: E501
        :rtype: str
        """
        return self._report_time

    @report_time.setter
    def report_time(self, report_time):
        """Sets the report_time of this MessagesResponseDataAbuseComplaints.

        Time when the complaint was made  # noqa: E501

        :param report_time: The report_time of this MessagesResponseDataAbuseComplaints.  # noqa: E501
        :type report_time: str
        """

        self._report_time = report_time

    @property
    def provider(self):
        """Gets the provider of this MessagesResponseDataAbuseComplaints.  # noqa: E501

        Abuse provider information  # noqa: E501

        :return: The provider of this MessagesResponseDataAbuseComplaints.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this MessagesResponseDataAbuseComplaints.

        Abuse provider information  # noqa: E501

        :param provider: The provider of this MessagesResponseDataAbuseComplaints.  # noqa: E501
        :type provider: str
        """

        self._provider = provider

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessagesResponseDataAbuseComplaints):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MessagesResponseDataAbuseComplaints):
            return True

        return self.to_dict() != other.to_dict()
