# coding: utf-8

# flake8: noqa

"""
    SMTP Public API overview

    SMTP.com Public API v4  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: support@smtp.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from smtp.api.api_keys_api import APIKeysApi
from smtp.api.account_api import AccountApi
from smtp.api.alerts_api import AlertsApi
from smtp.api.callbacks_api import CallbacksApi
from smtp.api.channels_api import ChannelsApi
from smtp.api.dki_ms_api import DKIMsApi
from smtp.api.messages_api import MessagesApi
from smtp.api.reports_api import ReportsApi
from smtp.api.statistics_api import StatisticsApi

# import ApiClient
from smtp.api_client import ApiClient
from smtp.configuration import Configuration
from smtp.exceptions import OpenApiException
from smtp.exceptions import ApiTypeError
from smtp.exceptions import ApiValueError
from smtp.exceptions import ApiKeyError
from smtp.exceptions import ApiAttributeError
from smtp.exceptions import ApiException
# import models into sdk package
from smtp.models.api_key import APIKey
from smtp.models.account import Account
from smtp.models.account_data import AccountData
from smtp.models.account_data_address import AccountDataAddress
from smtp.models.bad_request_schema import BadRequestSchema
from smtp.models.bad_request_schema_data import BadRequestSchemaData
from smtp.models.channel import Channel
from smtp.models.channel_data import ChannelData
from smtp.models.channels import Channels
from smtp.models.channels_data import ChannelsData
from smtp.models.channels_data_items import ChannelsDataItems
from smtp.models.create_callback_response import CreateCallbackResponse
from smtp.models.create_dkim_key import CreateDkimKey
from smtp.models.create_dkim_key_data import CreateDkimKeyData
from smtp.models.create_domain_response import CreateDomainResponse
from smtp.models.create_domain_response_data import CreateDomainResponseData
from smtp.models.duration_value import DurationValue
from smtp.models.get_alert_details import GetAlertDetails
from smtp.models.get_alert_details_data import GetAlertDetailsData
from smtp.models.get_alert_response import GetAlertResponse
from smtp.models.get_alert_response_data import GetAlertResponseData
from smtp.models.get_alert_response_data_items import GetAlertResponseDataItems
from smtp.models.get_api_keys import GetApiKeys
from smtp.models.get_api_keys_data import GetApiKeysData
from smtp.models.get_api_keys_data_items import GetApiKeysDataItems
from smtp.models.get_callback_details import GetCallbackDetails
from smtp.models.get_callback_details_data import GetCallbackDetailsData
from smtp.models.get_callback_logs import GetCallbackLogs
from smtp.models.get_callback_logs_data import GetCallbackLogsData
from smtp.models.get_callback_logs_data_items import GetCallbackLogsDataItems
from smtp.models.get_callback_response import GetCallbackResponse
from smtp.models.get_callback_response_data import GetCallbackResponseData
from smtp.models.get_callback_response_data_items import GetCallbackResponseDataItems
from smtp.models.get_domain_details import GetDomainDetails
from smtp.models.get_domain_details_data import GetDomainDetailsData
from smtp.models.get_domain_details_response import GetDomainDetailsResponse
from smtp.models.get_domain_details_response_data import GetDomainDetailsResponseData
from smtp.models.get_domains_response import GetDomainsResponse
from smtp.models.get_domains_response_data import GetDomainsResponseData
from smtp.models.get_domains_response_data_items import GetDomainsResponseDataItems
from smtp.models.inline_object import InlineObject
from smtp.models.inline_object1 import InlineObject1
from smtp.models.invalid_key import InvalidKey
from smtp.models.invalid_key_data import InvalidKeyData
from smtp.models.invalid_key_data_errors import InvalidKeyDataErrors
from smtp.models.messages_response import MessagesResponse
from smtp.models.messages_response_data import MessagesResponseData
from smtp.models.messages_response_data_abuse import MessagesResponseDataAbuse
from smtp.models.messages_response_data_abuse_complaints import MessagesResponseDataAbuseComplaints
from smtp.models.messages_response_data_clicks import MessagesResponseDataClicks
from smtp.models.messages_response_data_clicks_items import MessagesResponseDataClicksItems
from smtp.models.messages_response_data_details import MessagesResponseDataDetails
from smtp.models.messages_response_data_details_delivery import MessagesResponseDataDetailsDelivery
from smtp.models.messages_response_data_items import MessagesResponseDataItems
from smtp.models.messages_response_data_msg_data import MessagesResponseDataMsgData
from smtp.models.messages_response_data_opens import MessagesResponseDataOpens
from smtp.models.messages_response_data_opens_items import MessagesResponseDataOpensItems
from smtp.models.messages_response_data_unsubs import MessagesResponseDataUnsubs
from smtp.models.messages_response_data_unsubs_items import MessagesResponseDataUnsubsItems
from smtp.models.mime_response import MimeResponse
from smtp.models.post_message_response import PostMessageResponse
from smtp.models.post_message_response_data import PostMessageResponseData
from smtp.models.report import Report
from smtp.models.reports import Reports
from smtp.models.reports_data import ReportsData
from smtp.models.reports_data_ondemand import ReportsDataOndemand
from smtp.models.reports_data_periodic import ReportsDataPeriodic
from smtp.models.slice_value import SliceValue
from smtp.models.stats_response import StatsResponse
from smtp.models.stats_response_data import StatsResponseData
from smtp.models.stats_response_data_items import StatsResponseDataItems
from smtp.models.status_response import StatusResponse
from smtp.models.update_account_response import UpdateAccountResponse
from smtp.models.update_account_response_data import UpdateAccountResponseData
from smtp.models.v4_messages_body import V4MessagesBody
from smtp.models.v4_messages_body_attachments import V4MessagesBodyAttachments
from smtp.models.v4_messages_body_parts import V4MessagesBodyParts
from smtp.models.v4_messages_mime_recipients import V4MessagesMimeRecipients
from smtp.models.v4_messages_originator import V4MessagesOriginator
from smtp.models.v4_messages_recipients import V4MessagesRecipients
from smtp.models.v4_messages_recipients_to import V4MessagesRecipientsTo

